version: 2.1
orbs:
  docker: circleci/docker@2.1.3
parameters:
  tag:
    type: string
    default: 'latest'
  registry:
    type: string
    default: 'docker.io'
  repo:
    type: string
    default: 'deriv/perl'
aliases:
  - &filter_only_master
      branches:
        only:
          - /^master$/
  - &options_hadolint
      dockerfiles: Dockerfile:dzil/Dockerfile
      # Don't pin apt versions, we'll never remember to update them
      ignore-rules: DL3008,SC2046,DL3003,DL4006,DL3006,DL3005
  - &options_workflow_perl
      context: perl
      name: perl
  - &options_workflow_perl_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_perl
  - &options_workflow_dzil
      requires:
        - perl
      context: perl
      name: dzil
      image: deriv/dzil
      path: dzil/
      docker-context: dzil/
  - &options_workflow_dzil_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_dzil
jobs:
  build_and_publish:
    executor:
      name: docker/machine
      image: ubuntu-2004:202107-02
    parameters:
      push:
        type: boolean
        default: false
      image:
        type: string
        default: deriv/perl
      path:
        type: string
        default: .
      docker-context:
        type: string
        default: .
    steps:
      - checkout
      - docker/build:
          image: <<parameters.image>>
          path: <<parameters.path>>
          docker-context: <<parameters.docker-context>>
          tag: 'latest'
      - when:
          condition: <<parameters.push>>
          steps:
            - run:
                name: Docker Hub login
                command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            - docker/push:
                image: <<parameters.image>>
                tag: 'latest'
  create_arm64_image:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium
    environment:
      - DOCKER_REGISTRY: <<pipeline.parameters.registry>>
      - DOCKER_REPO: <<pipeline.parameters.repo>>
    steps:
      - checkout
      - run:
          name: 'Docker build'
          command: |
            docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:arm64-${CIRCLE_SHA1} .
            docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:arm64-${CIRCLE_SHA1}

  create_amd64_image:
    machine:
      image: ubuntu-2204:2022.07.1
    environment:
      - DOCKER_REGISTRY: <<pipeline.parameters.registry>>
      - DOCKER_REPO: <<pipeline.parameters.repo>>
    steps:
      - checkout
      - run:
          name: 'Docker build'
          command: |
            docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:amd64-${CIRCLE_SHA1} .
            docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:amd64-${CIRCLE_SHA1}

workflows:
  version: 2
  build-workflow:
    jobs:
      - create_arm64_image
      - create_amd64_image
      - build_and_publish: *options_workflow_perl
      - build_and_publish: *options_workflow_dzil
      - docker/hadolint: *options_hadolint
          
  merged:
    jobs:
      - build_and_publish: *options_workflow_perl_push
      - build_and_publish: *options_workflow_dzil_push
      - docker/hadolint:
          <<: *options_hadolint
          filters: *filter_only_master
  tagged:
    jobs:
      - build_and_publish: *options_workflow_perl_push
      - build_and_publish: *options_workflow_dzil_push
  daily:
    jobs:
      - build_and_publish: *options_workflow_perl_push
      - build_and_publish: *options_workflow_dzil_push
      - docker/hadolint: *options_hadolint
    triggers:
      - schedule:
          cron: 05 19 * * *
          filters: *filter_only_master
