version: 2.1
orbs:
  docker: circleci/docker@2.1.3
parameters:
  tag:
    type: string
    default: 'latest'
  registry:
    type: string
    default: 'docker.io'
aliases:
  - &filter_only_master
      branches:
        only:
          - /^master$/
  - &options_hadolint
      dockerfiles: Dockerfile:dzil/Dockerfile
      # Don't pin apt versions, we'll never remember to update them
      ignore-rules: DL3008,SC2046,DL3003,DL4006,DL3006,DL3005
  - &options_workflow_perl
      context: perl
      image: deriv/perl
  - &options_workflow_perl_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_perl
  - &options_workflow_dzil
      context: perl
      image: deriv/dzil
      path: dzil/
      docker-context: dzil/
  - &options_workflow_dzil_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_dzil
jobs:
  build_amd64:
    executor:
      name: docker/machine
      image: ubuntu-2204:2022.07.1
    parameters:
      image:
        type: string
        default: deriv/perl
      path:
        type: string
        default: .
      docker-context:
        type: string
        default: .
    steps:
      - checkout
      - docker/build:
          image: <<parameters.image>>
          path: <<parameters.path>>
          docker-context: <<parameters.docker-context>>
          tag: amd64-<<pipeline.parameters.tag>>
  build_arm64:
    executor:
      name: docker/machine
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium
    parameters:
      image:
        type: string
        default: deriv/perl
      path:
        type: string
        default: .
      docker-context:
        type: string
        default: .
    steps:
      - checkout
      - docker/build:
          image: <<parameters.image>>
          path: <<parameters.path>>
          docker-context: <<parameters.docker-context>>
          tag: arm64-<<pipeline.parameters.tag>>
  publish:
    executor: docker/docker
    parameters:
      image:
        type: string
        default: deriv/perl
      push:
        type: boolean
        default: false
      path:
        type: string
        default: .
      docker-context:
        type: string
        default: .
    steps:
      - docker/configure-docker-credentials-store
      - docker/install-docker-credential-helper
      - docker/check
      - docker/dockerlint
      - when:
          condition: <<parameters.push>>
          steps:
            - deploy:
                name: "Upload manifest to registry"
                command: |
                  set -eu
                  export DOCKER_CLI_EXPERIMENTAL=enabled
                  docker manifest create \
                    ${DOCKER_REGISTRY}/<<parameters.image>>:<<pipeline.parameters.tag>> \
                    ${DOCKER_REGISTRY}/<<parameters.image>>:arm64-<<pipeline.parameters.tag>> \
                    ${DOCKER_REGISTRY}/<<parameters.image>>:amd64-<<pipeline.parameters.tag>>
                  docker manifest push ${DOCKER_REGISTRY}/<<parameters.image>>:<<pipeline.parameters.tag>>

workflows:
  version: 2
  build-workflow:
    jobs:
      - build_amd64:
          <<: *options_workflow_perl
          name: perl_amd64
      - build_arm64:
          <<: *options_workflow_perl
          name: perl_arm64
      - publish:
          <<: *options_workflow_perl
          name: publish_perl
          context: perl
          requires:
            - perl_amd64
            - perl_arm64
          push: true
      - build_amd64:
          <<: *options_workflow_dzil
          name: dzil_amd64
          requires:
            - publish_perl
      - build_arm64:
          <<: *options_workflow_dzil
          name: dzil_arm64
          requires:
            - publish_perl
      - publish:
          <<: *options_workflow_dzil
          name: publish_dzil
          context: perl
          requires:
            - dzil_amd64
            - dzil_arm64
          push: true
      - docker/hadolint: *options_hadolint
          
#  merged:
#    jobs:
#      - build_and_publish: *options_workflow_perl_push
#      - build_and_publish: *options_workflow_dzil_push
#      - docker/hadolint:
#          <<: *options_hadolint
#          filters: *filter_only_master
#  tagged:
#    jobs:
#      - build_and_publish: *options_workflow_perl_push
#      - build_and_publish: *options_workflow_dzil_push
#  daily:
#    jobs:
#      - build_and_publish: *options_workflow_perl_push
#      - build_and_publish: *options_workflow_dzil_push
#      - docker/hadolint: *options_hadolint
#    triggers:
#      - schedule:
#          cron: 05 19 * * *
#          filters: *filter_only_master
