version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          command: |
              sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
              docker run --privileged --rm tonistiigi/binfmt --install arm64
              docker context create ctx
              docker buildx create --use --driver docker-container --platform linux/arm64,linux/arm/v8,linux/amd64 ctx
      - run: docker buildx inspect --bootstrap
      - run: docker buildx build --platform linux/amd64,linux/arm64 --progress plain --pull --push -t docker.io/deriv/perl:multi-platform .
      - run: docker buildx build --platform linux/amd64,linux/arm64 --progress plain --pull --push -t docker.io/deriv/dzil:multi-platform dzil/
