version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  version: 2
  build-workflow:
    jobs:
      - docker/publish:
          deploy: false
          image: deriv/perl
      - docker/publish:
          deploy: false
          image: deriv/dzil
          path: dzil
      - docker/hadolint:
          dockerfiles: Dockerfile:dzil/Dockerfile
          # Don't pin apt versions, we'll never remember to update them
          ignore-rules: DL3008
  merged:
    jobs:
      - docker/publish:
          deploy: true
          image: deriv/perl
          filters:
            branches:
              only: /^master$/
      - docker/publish:
          deploy: true
          image: deriv/dzil
          path: dzil
          filters:
            branches:
              only: /^master$/
      - docker/hadolint:
          dockerfiles: Dockerfile:dzil/Dockerfile
          # Don't pin apt versions, we'll never remember to update them
          ignore-rules: DL3008
          filters:
            branches:
              only: /^master$/
  tagged:
    jobs:
      - docker/publish:
          deploy: true
          image: deriv/perl
          filters:
            branches:
              only: /^master$/
      - docker/publish:
          deploy: true
          image: deriv/dzil
          path: dzil
          filters:
            branches:
              only: /^master$/
  daily:
    jobs:
      - docker/publish:
          deploy: false
          image: deriv/perl
      - docker/publish:
          deploy: false
          image: deriv/dzil
          path: dzil
      - docker/hadolint:
          dockerfiles: Dockerfile:dzil/Dockerfile
          # Don't pin apt versions, we'll never remember to update them
          ignore-rules: DL3008
    triggers:
      - schedule:
          cron: 05 19 * * *
          filters:
            branches:
              only:
              - master
