version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run: docker buildx build --platform linux/amd64,linux/arm64 --pull --push -t docker.io/deriv/perl:multi-platform .
      - run: docker buildx build --platform linux/amd64,linux/arm64 --pull --push -t docker.io/deriv/dzil:multi-platform dzil/
