version: 2.1
orbs:
  docker: circleci/docker@1.4.0
aliases:
  - &filter_only_master
      branches:
        only:
          - /^master$/
  - &options_hadolint
      dockerfiles: Dockerfile:dzil/Dockerfile
      # Don't pin apt versions, we'll never remember to update them
      ignore-rules: DL3008,SC2046,DL3003,DL4006,DL3006
  - &options_workflow_perl
      context: perl
      name: perl
  - &options_workflow_perl_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_perl
  - &options_workflow_dzil
      requires:
        - perl
      context: perl
      name: dzil
      image: deriv/dzil
      path: dzil/
      docker-context: dzil/
  - &options_workflow_dzil_push
      push: true
      filters: *filter_only_master
      <<: *options_workflow_dzil
jobs:
  build_and_publish:
    executor: docker/docker
    parameters:
      push:
        type: boolean
        default: false
      image:
        type: string
        default: deriv/perl
      path:
        type: string
        default: .
      docker-context:
        type: string
        default: .
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: <<parameters.image>>
          path: <<parameters.path>>
          docker-context: <<parameters.docker-context>>
      - when:
          condition: <<parameters.push>>
          steps:
            - run:
                name: Docker Hub login
                command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            - docker/push:
                image: <<parameters.image>>
workflows:
  version: 2
  build-workflow:
    jobs:
      - build_and_publish: *options_workflow_perl
      - build_and_publish: *options_workflow_dzil
      - docker/hadolint: *options_hadolint
          
  merged:
    jobs:
      - build_and_publish: *options_workflow_perl_push
      - build_and_publish: *options_workflow_dzil_push
      - docker/hadolint:
          <<: *options_hadolint
          filters: *filter_only_master
  tagged:
    jobs:
      - build_and_publish: *options_workflow_perl_push
      - build_and_publish: *options_workflow_dzil_push
  daily:
    jobs:
      - build_and_publish: *options_workflow_perl
      - build_and_publish: *options_workflow_dzil
      - docker/hadolint: *options_hadolint
    triggers:
      - schedule:
          cron: 05 19 * * *
          filters: *filter_only_master
