name: Build And Publish
description: 'Builds the docker image and can also publish the built image'
inputs:
  publish:
    description: 'Flag to whether the image should be published or not'
    default: 'false'
    required: false
  image:
    description: 'Name of newly built image'
    required: true
  build-context:
    description: 'Build context for the docker image'
    default: '.'
    required: false
runs:
  using: composite
  steps:
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.build-context }}
        push: ${{ inputs.publish }}
        tags: ${{ inputs.image }}
    