name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Build Docker Image
        uses: ./.github/actions/build_and_publish
        with:
          publish: false
          image: deriv/perl:latest 
      -
        name: Docker image info
        run: docker image ls
