name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: '.'
          tags: deriv/perl
          push: false
  dzil:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: 'dzil/'
          tags: deriv/dzil
          push: false   
      -
        name: docker image info
        run: docker image ls 
  hadolint:
    uses: ./.github/workflows/hadolint.yml
    with:
      ignore-rules: 'DL3008,SC2046,DL3003,DL4006,DL3006,DL3005'
      dockerfiles: 'Dockerfile:dzil/Dockerfile'
