name: Build images

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build images
        run: |
          docker version
          [ -n $DEBIAN_PROXY ] && docker_build_opts="--build-arg=DEBIAN_PROXY=${DEBIAN_PROXY}"
          docker build "$docker_build_opts" -t deriv/perl .
          cd dzil && docker build "$docker_build_opts" -t deriv/dzil .
      - name: Inspect image creation and tag time
        run: |
          docker image inspect --format \'{{.Created}}\' deriv/perl
          docker image inspect --format \'{{.Metadata.LastTagTime}}\' deriv/perl
          docker image inspect --format \'{{.Created}}\' deriv/dzil
          docker image inspect --format \'{{.Metadata.LastTagTime}}\' deriv/dzil
